### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'input_size'

### ISSUE THREAD

**Issue by SeekPoint** [HKUST-KnowComp/R-Net#14]
$ python config.py --mode train
Building model...
Traceback (most recent call last):
  File "config.py", line 127, in <module>
    tf.app.run()
  File "/Users//ve_tf1.5_py3/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "config.py", line 108, in main
    train(config)
  File "/Users//R-Net-tf/main.py", line 35, in train
    model = Model(config, iterator, word_mat, char_mat)
  File "/Users//R-Net-tf/model.py", line 43, in __init__
    self.ready()
  File "/Users//R-Net-tf/model.py", line 92, in ready
    ).as_list()[-1], keep_prob=config.keep_prob, is_train=self.is_train)
  File "/Users//R-Net-tf/func.py", line 18, in __init__
    num_layers=1, num_units=num_units, input_size=input_size_)
TypeError: __init__() got an unexpected keyword argument 'input_size'

**Comment by wzhouad** [comment]
The model requires Tensorflow 1.4. Please check your TF version.

**Comment by SeekPoint** [comment]
yes, I use tf1.5

it works with tf1.4
